### ISSUE TITLE
Map leaderboards layout needs to follow the mockup

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#158]
Leaderboards.png

**Comment by Gocnak** [comment]
... that commit doesn't close this issue. That added the headers, but the content still needs displaying and formatting.

**Comment by lubna9** [comment]
Leaderboard data are now formatted 
![image](https://user-images.githubusercontent.com/43045440/49340411-5f60fe80-f60d-11e8-9a6f-b6b4df31cad2.png)
however, I don't know what you mean by they need to display. I believe Corey made it so that it pulls real data. when there is none, nothing will show up... 
Do you want me to hard code fake data?

**Comment by Gocnak** [comment]
No need to hardcode anything. "NAME" needs to change to "USER" and use an `<nb-user>` to show name and avatar, and consider checking out #160 as well.
