### ISSUE TITLE
Hook up Run History filters

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#252]
Currently there just not hooked up

**Comment by vindow** [comment]
So if you apply the filters client-side you'll run into some issues with pagination and filtering. You can get a page of no results since the search result might be on the next page of 10 unfiltered results. Here's a picture example: 

![example](https://user-images.githubusercontent.com/5974776/103715459-8a00ac80-4f75-11eb-8a97-43d81aa5c23d.png)

Would it be better to just re-query from the backend with filter params (probably requires some backend reworking) so you can get a list of 10 filtered results per page? This issue somewhat applies to other lists of things too (such as activities) but it's more noticeable with the pagination of the user runs list.

**Comment by Gocnak** [comment]
Yeah it would be better to just re-query upon applying the filters. Could have them auto-apply with a debounce like the searching does, or just for now, use the Apply button and see if people think that's good enough.
