### ISSUE TITLE
User activity does not respect AVATAR_BANNED user ban

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#345]
If you ban a user's avatar their avatar still shows in the activity feed.

It probably isn't the only instance of this, so make sure to check everywhere the user's avatar is used to make sure if they're banned, that it uses the correct "default" avatar image.

**Comment by Corey28** [comment]
Not sure if it'd be better to implement this on the server side or the client side. A pretty minimal server side approach would be to do a custom sequelize getter for the avatar URL, which does a check on the user bans, and if they are banned, return the "default" avatar image URL instead of the normal image URL

**Comment by Gocnak** [comment]
Closed by https://github.com/momentum-mod/website/commit/a84515e686f0061fe394fa4affebe20ff1a7ee70
