### ISSUE TITLE
More CI improvements - caching builds

### ISSUE THREAD

**Issue by Hona** [momentum-mod/website#424]
From discussion with Gocnak, we decided to do the following to save some build time, as the build is ~15 minutes, and it would be nice to try to reduce this.

On PR:
- Travis:
   - Tests
- GitHub Action:
   - check cache for server/client stuff
   - install client dependencies
   - Build client:prod
   - yarn install server stuff?
   - cache server and client dependencies
   - output dist/ as artifact

On merge:
- GitHub Action (build Dockerfile):
   - Pull in cache for server dependencies
   - pull in client:prod build output (/dist/)
   - create local folders as Dockerfile sees fit for mounting
   - create Dockerfile with the server part of the Dockerfile as normal (build server packages using cache and mounted /dist/)

> Gocnak: And with a proper cache I'm expecting this to take no longer than 10 minutes combined, as the Travis build for the client only took 6 minutes, including caching things

**Comment by Gocnak** [comment]
Status update on this:

#484 did a lot of great work to cache things, leading to the server tests taking under a minute, and client tests taking ~3-4 minutes. AngularBuild still happens (and catches things from time to time) but its output isn't used, which takes the longest time, ~8 mins.

Client "prod" build is now manually triggered and while it takes around 6 minutes, can't really do too much other than reduce dependencies in Angular somehow (same for AngularBuild).

Server docker file build takes under 2 minutes, which could be better with package caching there I think. Most of the time is actually building and publishing the dockerfile itself, so we would be shaving more of the `RUN yarn install` step there.


As we still have more work to do, this is pretty satisfactory for the time being. Maybe in the future (post backend TypeScript port) we can look into further caching gains, and make specific cards for the actions to take instead of monolithic mega ones like this one.
