### ISSUE TITLE
Dashboard background is not removed when navigating back to main page

### ISSUE THREAD

**Issue by wallenben** [momentum-mod/website#526]
![image](https://user-images.githubusercontent.com/72104872/127613187-da4df130-d60b-4b1b-87d9-bc39ee6301e3.png)

Looks like if you access the dashboard and navigate back to the main page, the background is cached and overlaps with the video. This is due to a pseudo ::before element (background). Probably just needs to update the background tag (null it out) or use a different approach - will r&d

Edit: might be hard to test, I assume adding `background: none` to header.component.ts should fix the issue, but I cannot recreate it locally as the bug uses the dashboard - see relevant [commit](https://github.com/comatoad/website/commit/8e462de82e97b4e90b359be9cffb5a335e8f2b3d)

**Comment by bakapear** [comment]
Just comment out [this line](https://github.com/momentum-mod/website/blob/49798e61e2d4dc3261c9fc27f930d331a1867a7c/client/src/app/app-routing.module.ts#L15) and you can visit `/dashboard` without having a backend running. It's limited but does help develop!

And from testing myself, adding `background: none` to masthead does not fix the issue, as the pseudo ::before is added onto the body tag of the page I assume.

But rather than fixing it like this, why not change the dashboard background to be the same as on the frontpage? The current one used doesn't look that appealing in my opinion.

**Comment by comatoad** [comment]
I would definitely agree that it could use a refresher - full video might be a bit much. Maybe the static image could be a suitable replacement, I'll check that out
