### ISSUE TITLE
Optimizing the map search component further with two-way bindings

### ISSUE THREAD

**Issue by wallenben** [momentum-mod/website#536]
Extension of discussion on #534 
Currently, map data is handled through a form. Refactoring the map form and the game-mode dropdown to be more efficient with API usage is possible, so it's definitely worth looking into.

![image](https://user-images.githubusercontent.com/72104872/129456064-3225eb47-b76d-41d3-8db6-ed82447175c3.png)

Relevant discussion points from TheNerdMan:

> I'd set up two way bindings on the text field, and dropdown. Have a "onChange" event that fires when text changes,drop down changes or button is clicked. Then that "onChange" event will check those twoway binding values and makes the appropriate API call. 

> [You should] hook up the two-way bindings to the state's properties, that way if there are other map filtering places, those search elements will be saved and reused

Further examples are posted in the webdev channel in discord.

**Comment by tsa96** [comment]
Bit confused by this issue. I agree with Alex that we should use a two-way binding here instead of a form, so users don't have to press enter or a "search" button - I'll do that in my incoming PR.

This isn't a performance optimisation though, we'll be making more queries. But I don't think the performance is very in important here as the queries are relatively cheap, since
- this list doesn't need to fetch a ton of data about each map, really just the primary table and the thumbnail, so only one join
- the MMap table is relatively small, but queried a lot. so it can have a whole bunch of indexes on at minimal costs
- the frontend doesn't get used that much

So my incoming PR will essentially implement this and close this issue.

**Comment by tsa96** [comment]
Okay, incoming PR will close this. Two way binding isn't needed, Angular forms are perfectly capable of handling this - just use a subscription to the `FormGroup.valueChanges` observable.
