### ISSUE TITLE
♻️ Use tsoa to generate TypeScript backend API docs

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/website#558]
https://github.com/lukeautry/tsoa

swagger-autogen is nice but requires a ton of comment-based documentation, where when we're porting fully to TypeScript anyways, we can add things like decorators to document our TypeScript-ified routes.

**Comment by TheNerdMan** [comment]
Working on this, I have a feat open on my local machine (forgot it check in due to tiredness). My thought is to build up the API routes using an example project, then when it's ready import those routes into the existing project on top of the existing code.

This would mean our existing code would become the service/business layer and our controllers would be abstracted above them. Pushing us towards a better Controller->Business access layer->Data access layer data flow. (Compared to the existing Controller -> Business/Data layer)

**Comment by TheNerdMan** [comment]
https://github.com/momentum-mod/website/projects/4

**Comment by TheNerdMan** [comment]
Since switching to NestJS this issue is no longer needed.
See #582
